

INSERT INTO profession (name) VALUES ('Acteur');
INSERT INTO profession (name) VALUES ('Actrice');
INSERT INTO profession (name) VALUES ('Réalisateur');
INSERT INTO profession (name) VALUES ('Producteur');
INSERT INTO profession (name) VALUES ('Producteur exécutif');
INSERT INTO profession (name) VALUES ('Producteur associé');
INSERT INTO profession (name) VALUES ('Scénariste');
INSERT INTO profession (name) VALUES ('Auteur');
INSERT INTO profession (name) VALUES ('Co-auteur');
INSERT INTO profession (name) VALUES ('Superviseur de script');
INSERT INTO profession (name) VALUES ('Compositeur');
INSERT INTO profession (name) VALUES ('Chef d’orchestre');
INSERT INTO profession (name) VALUES ('Superviseur musical');
INSERT INTO profession (name) VALUES ('Concepteur sonore');
INSERT INTO profession (name) VALUES ('Monteur son');
INSERT INTO profession (name) VALUES ('Cadreur');
INSERT INTO profession (name) VALUES ('Directeur de la photographie');
INSERT INTO profession (name) VALUES ('Opérateur caméra');
INSERT INTO profession (name) VALUES ('Monteur');
INSERT INTO profession (name) VALUES ('Coloriste');
INSERT INTO profession (name) VALUES ('Directeur de casting');
INSERT INTO profession (name) VALUES ('Maquilleur');
INSERT INTO profession (name) VALUES ('Costumier');
INSERT INTO profession (name) VALUES ('Directeur artistique');
INSERT INTO profession (name) VALUES ('Chef décorateur');
INSERT INTO profession (name) VALUES ('Décorateur de plateau');
INSERT INTO profession (name) VALUES ('Chef électricien');
INSERT INTO profession (name) VALUES ('Chef machiniste');
INSERT INTO profession (name) VALUES ('Machiniste');
INSERT INTO profession (name) VALUES ('Coordinateur des cascades');
INSERT INTO profession (name) VALUES ('Cascadeur');
INSERT INTO profession (name) VALUES ('Superviseur effets visuels');
INSERT INTO profession (name) VALUES ('Technicien effets spéciaux');
INSERT INTO profession (name) VALUES ('Technicien lumière');
INSERT INTO profession (name) VALUES ('Directeur de production');
INSERT INTO profession (name) VALUES ('Directeur de production délégué');
INSERT INTO profession (name) VALUES ('Assistant de production');
INSERT INTO profession (name) VALUES ('Perchman');
INSERT INTO profession (name) VALUES ('Bruiteur');
INSERT INTO profession (name) VALUES ('Animateur');
INSERT INTO profession (name) VALUES ('Voix off');
INSERT INTO profession (name) VALUES ('Responsable des lieux de tournage');
INSERT INTO profession (name) VALUES ('Storyboarder');
INSERT INTO profession (name) VALUES ('Monteur (image)');
INSERT INTO profession (name) VALUES ('Coach de dialogue');
INSERT INTO profession (name) VALUES ('Coach de dialecte');

