TRUNCATE TABLE playlist_element RESTART IDENTITY CASCADE;
TRUNCATE TABLE playlist RESTART IDENTITY CASCADE;

TRUNCATE TABLE media_person RESTART IDENTITY CASCADE;
TRUNCATE TABLE media RESTART IDENTITY CASCADE;
TRUNCATE TABLE media_type RESTART IDENTITY CASCADE;

TRUNCATE TABLE person_profession RESTART IDENTITY CASCADE;
TRUNCATE TABLE profession RESTART IDENTITY CASCADE;

TRUNCATE TABLE person RESTART IDENTITY CASCADE;
TRUNCATE TABLE city RESTART IDENTITY CASCADE;
TRUNCATE TABLE country RESTART IDENTITY CASCADE;
TRUNCATE TABLE continent RESTART IDENTITY CASCADE;
