name: backend-springboot

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-springboot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # - name: Lint (Checkstyle)
      #   run: mvn checkstyle:check

      - name: Run unit tests
        run: mvn clean test

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Build project
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-springboot:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-springboot:latest
